export const CREATE_CONNECT_ACCOUNT_REQUEST = 'CREATE_CONNECT_ACCOUNT_REQUEST';
export const CREATE_CONNECT_ACCOUNT_SUCCESS = 'CREATE_CONNECT_ACCOUNT_SUCCESS';
export const CREATE_CONNECT_ACCOUNT_FAIL = 'CREATE_CONNECT_ACCOUNT_FAIL';

export const GET_ACCOUNT_STATUS_REQUEST = 'GET_ACCOUNT_STATUS_REQUEST';
export const GET_ACCOUNT_STATUS_SUCCESS = 'GET_ACCOUNT_STATUS_SUCCESS';
export const GET_ACCOUNT_STATUS_FAIL = 'GET_ACCOUNT_STATUS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
